language: objective-c
xcode_workspace: SwiftFP.xcworkspace
xcode_scheme: SwiftFP
xcode_sdk: iphonesimulator10.1
before_install:
- gem install cocoapods slather
- pod repo update

script:
- set -o pipefail && xcodebuild test -workspace SwiftFP.xcworkspace -scheme SwiftFP -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 7 Plus"
- pod lib lint --quick

after_success: slather
