osx_image: xcode10.2
language: objective-c
xcode_workspace: SwiftFP.xcworkspace
xcode_scheme: SwiftFP
xcode_sdk: iphonesimulator12.1
before_install:
  - gem install cocoapods
  - gem install slather
  - gem install xcpretty
  - pod install

script:
  - set -o pipefail && xcodebuild clean test -sdk iphonesimulator -workspace SwiftFP.xcworkspace -scheme SwiftFP -destination 'platform=iOS Simulator,name=iPhone 8 Plus' | xcpretty
  - pod lib lint --quick

after_success: slather
